version: '3'
services:
  common-environment:
    container_name: common-environment
    image: quay.io/ceph/daemon:latest-quincy
    platform: linux/amd64
    env_file: .env  # Load environment variables from the .env file
    volumes:
      - ceph-conf-volume:/etc/ceph:rw
      - ceph-lib-volume:/var/lib/ceph:rw
      - ceph-script-volume:/opt/ceph-container/bin/
      - ceph-media-volume:/etc/resources:rw
      - ceph-osd1-volume:/var/lib/ceph/osd/ceph-0:rw
      - ceph-osd2-volume:/var/lib/ceph/osd/ceph-1:rw
      - ceph-osd3-volume:/var/lib/ceph/osd/ceph-2:rw
      - ./.s3cfg:/root/.s3cfg
  ceph-mon:
    extends:
      service: common-environment
    container_name: ceph-mon
    hostname: ceph-mon
    restart: always
    command: mon_bootstrap
    networks:
      ceph-net:
        ipv4_address: 192.168.55.2
    ports:
      - '6789:6789'

  ceph-mgr:
    extends:
      service: common-environment
    container_name: ceph-mgr
    hostname: ceph-mgr
    restart: always
    command: mgr_bootstrap
    networks:
      ceph-net:
        ipv4_address: 192.168.55.3
    ports:
      - '8443:8443'

  ceph-osd1:
    pid: host
    privileged: true
    extends:
      service: common-environment
    environment:
      OSD_ID: 0
    container_name: ceph-osd1
    hostname: ceph-osd1
    command: osd_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.4

  ceph-osd2:
    pid: host
    privileged: true
    extends:
      service: common-environment
    environment:
      OSD_ID: 1
    container_name: ceph-osd2
    hostname: ceph-osd2
    command: osd_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.5

  ceph-osd3:
    pid: host
    privileged: true
    extends:
      service: common-environment
    environment:
      OSD_ID: 2
    container_name: ceph-osd3
    hostname: ceph-osd3
    command: osd_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.6

  ceph-rgw:
    extends:
      service: common-environment
    hostname: ceph-rgw
    container_name: ceph-rgw
    command: rgw_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.7
    ports:
      - '7480:7480'

  ceph-mds:
    extends:
      service: common-environment
    platform: linux/amd64
    container_name: ceph-mds
    command: mds_bootstrap
    hostname: ceph-mds
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.8

  ceph-rbd:
    extends:
      service: common-environment
    hostname: ceph-rbd
    container_name: ceph-rbd
    command: rbd_mirror_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.9

  ceph-nfs:
    extends:
      service: common-environment
    hostname: ceph-nfs
    container_name: ceph-nfs
    command: nfs_bootstrap
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.10


volumes:
  ceph-media-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/resources/
  ceph-script-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/scripts/
  ceph-conf-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/ceph_conf/
  ceph-lib-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/ceph_data/
  ceph-osd1-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/osds/osd1/
  ceph-osd2-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/osds/osd2/
  ceph-osd3-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/osds/osd3/

networks:
  ceph-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
