version: '3'
services:
  common-environment:
    container_name: common-environment
    image: ceph-daemon:latest
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/lib/systemd/systemd' ]
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env  # Load environment variables from the .env file
    volumes:
      - ./ceph_conf/${CEPH_FSID}:/etc/ceph:rw
      - ./ceph_data/${CEPH_FSID}:/var/lib/ceph:rw
      - ./ceph_data/${CEPH_FSID}/crash:/var/lib/ceph/crash:rw
      - ./ceph_log/${CEPH_FSID}:/var/log/ceph:rw
      - ./ceph_run/${CEPH_FSID}:/var/run/ceph:rw
      - ./scripts:/opt/ceph-container/bin/
      - ./resources:/etc/resources:rw
      - ./osds/osd1:/var/lib/ceph/osd/ceph-0:rw
      - ./osds/osd2:/var/lib/ceph/osd/ceph-1:rw
      - ./osds/osd3:/var/lib/ceph/osd/ceph-2:rw
      - ./.s3cfg:/root/.s3cfg:rw
      - ./.env:/root/.env:rw
  ceph-mon:
    extends:
      service: common-environment
    container_name: ceph-mon
    environment:
      MON_ID: 0
    hostname: ceph-mon
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.2
    ports:
      - '6789:6789'
      - '3300:3300'

  ceph-mgr:
    extends:
      service: common-environment
    container_name: ceph-mgr
    hostname: ceph-mgr
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.3
    ports:
      - '8443:8443'

  ceph-osd1:
    extends:
      service: common-environment
    environment:
      OSD_ID: 0
    container_name: ceph-osd1
    hostname: ceph-osd1
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.4

  ceph-osd2:
    extends:
      service: common-environment
    environment:
      OSD_ID: 1
    container_name: ceph-osd2
    hostname: ceph-osd2
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.5

  ceph-osd3:
    extends:
      service: common-environment
    environment:
      OSD_ID: 2
    container_name: ceph-osd3
    hostname: ceph-osd3
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.6

  ceph-rgw:
    extends:
      service: common-environment
    hostname: ceph-rgw
    container_name: ceph-rgw
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.7
    ports:
      - '7480:7480'

  ceph-mds:
    extends:
      service: common-environment
    platform: linux/amd64
    container_name: ceph-mds
    hostname: ceph-mds
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.8

  ceph-rbd:
    extends:
      service: common-environment
    hostname: ceph-rbd
    container_name: ceph-rbd
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.9

  ceph-nfs:
    extends:
      service: common-environment
    hostname: ceph-nfs
    container_name: ceph-nfs
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.10

  ceph-setup:
    extends:
      service: common-environment
    container_name: ceph-setup
    hostname: ceph-setup
    entrypoint: [ '/lib/systemd/systemd' ]
    restart: always
    networks:
      ceph-net:
        ipv4_address: 192.168.55.11
networks:
  ceph-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24

